query  {
            menus {
              edges {
                node {
                  id
                  name
                  menuItems {
                    nodes {
                      label
                      id
                      url
                    }
                  }
                }
              }
            }
          }