query {
  albums(where: {name: "parfois-encore"}) {
    edges {
      node {
        id
        slug
        acfAlbums {
        serieDimages {
          id
          mediaItemUrl
          title
        } 
      }
      }
    }
  }
}